### ISSUE TITLE
Update Background Image URL in CSS File

### ISSUE THREAD

**Issue by RanitManik** [EngAbdulazizGomaa/Intro-component-with-signup-form-master#1]
Everything looks great. However, the background image is not displaying because the path was entered incorrectly:

```css
.content {
    background-image: url("./images/bg-intro-desktop.png");
}
```
